name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set Git identity
      run: |
        git config --global user.name "$GIT_USERNAME"
        git config --global user.email "$GIT_EMAIL"
      env:
        GIT_USERNAME: ${{ secrets.USERNAME }}
        GIT_EMAIL: ${{ secrets.EMAIL }}
        
    - name: Deploy
      run: npm ci && npm run deploy
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
